ElectroElite4/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from apps.core.views import *
from apps.BancoDados.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('user/', include('apps.core.urls')),
    path('crud/', include('apps.BancoDados.urls')),
]

apps/BancoDados/urls.py
from django.urls import path
from .views import *

app_name = 'bancodados'

urlpatterns = [
    path('cadcategoria/', view_cadcategoria),
    path('create_categoria/', view_create_categoria, name='createcategoria'),
    path('cadcliente/', view_cadcliente),
    path('create_cliente/', view_create_cliente, name='createcliente'),
    path('caditenspedidos/', view_caditenspedidos, name='caditenspedidos'),
    path('create_itenspedidos/', view_create_itenspedidos, name='createitenspedidos'),
    path('cadmetpagamento/', view_cadmetpagamento),
    path('create_metpagamento/', view_create_metpagamento, name='createmetpagamento'),
    path('cadpedido/', view_cadpedido, name='cadpedido'),
    path('create_pedido/', view_create_pedido, name='createpedido'),
    path('cadproduto/', view_cadproduto, name="cadproduto"),
    path('create_produto/', view_create_produto, name='createproduto'),
]

apps/core/urls.py
from django.urls import path
from .views import *

app_name = 'usuarios'

urlpatterns = [
    path('', view_home, name='home'),
    path('login/', view_login, name='login'),
    path('login/acess', view_acess_login, name='acess'),
    path('login/logout', view_logout, name= 'logout'),
    path('cadusuario/', view_cadusuario, name='cadastro'),
    path('cadusuario/<int:firstacess>', view_cadusuario, name='cadastro'),
    path('cadusuario/create_usuario/', view_create_usuario, name='createusuario'),
    path('area_usuario', view_area_usuario, name='area_usuario'),
]

apps/BancoDados/models.py
from django.db import models

# Create your models here.

class Clientes(models.Model):
    idCliente = models.BigAutoField(primary_key=True)
    nomeCliente = models.CharField(max_length=300, null=False)
    cpf = models.CharField(max_length=11, null=False)
    telefone = models.CharField(max_length=15,null=False)
    email = models.CharField(max_length=300, null=False)
    endereco = models.CharField(max_length=300, null=False)

    class Meta:
        verbose_name_plural = "Clientes"
    
    def __str__(self):
        return "CPF: " + self.cpf + " - Nome: " + self.nomeCliente

class CategoriaProduto(models.Model):
    idCategoria = models.BigAutoField(primary_key=True)
    nomeCategoria = models.CharField(max_length=70, null=False)
    descricaoCategoria = models.CharField(max_length=300, null=True)

    class Meta:
        verbose_name_plural = "Categoria de Produtos"
    
    def __str__(self):
        return self.nomeCategoria

class MetodoPagamento(models.Model):
    idMetodoPagamento = models.IntegerField(primary_key=True)
    nomeMetodo = models.CharField(max_length=70, null=False)
    descricaoMetodo = models.CharField(max_length=300, null=True)

    class Meta:
        verbose_name_plural = "Metodos de Pagamento"
    
    def __str__(self):
        return self.nomeMetodo

class Pedidos(models.Model):
    idPedido = models.BigAutoField(primary_key=True)
    Clientes_idCliente = models.ForeignKey(Clientes, on_delete=models.PROTECT)
    DataEmissao = models.DateField(null=True,
                                    help_text="Formato <em>yyyy-MM-DD</em>")
    StatusPedido = models.CharField(max_length=45, null=False)
    MetodoPagamento_idMetodoPagamento = models.ForeignKey(MetodoPagamento, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "Pedidos"
    
    def __str__(self):
        return "ID: " + str(self.idPedido) + " | Cliente: " + str(self.Clientes_idCliente) + " | Status: " + str(self.StatusPedido)

class Produtos(models.Model):
    idProduto = models.BigAutoField(primary_key=True)
    NomeProduto = models.CharField(max_length=200,null=False)
    Preco = models.DecimalField(max_digits=10, decimal_places=2,null=False)
    Descricao = models.CharField(max_length=500,null=True)
    Estoque = models.IntegerField(null=False)
    CategoriaProduto_idCategoriaProduto = models.ForeignKey(CategoriaProduto, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "Produtos"
    
    def __str__ (self):
        return self.NomeProduto + " | Estoque: " + str(self.Estoque)

class ItensPedidos(models.Model):
    idItensPedidos = models.BigAutoField(primary_key=True)
    Quantidade = models.IntegerField(null=False)
    PrecoTotal = models.DecimalField(max_digits=10, decimal_places=2,null=False)
    Produto_idProduto = models.ForeignKey(Produtos, on_delete=models.PROTECT)
    Pedidos_idPedidos = models.ForeignKey(Pedidos, on_delete=models.PROTECT)

    class Meta:
        verbose_name_plural = "Itens Pedidos"
    
    def __str__(self):
        return "ID: " + str(self.idItensPedidos)

apps/BancoDados/forms.py
from django import forms
from .models import *

class RegisterCategoria(forms.ModelForm):
    class Meta:
        model = CategoriaProduto
        fields = '__all__'
        labels = {
                'idCategoria' : 'Identificação de Categoria',
                'nomeCategoria' : 'Nome da Categoria',
                'descricaoCategoria' : 'Descrição de categoria'
        }

        help_texts = {
            'nomeCategoria': 'Digite o nome da categoria.',
        }

        error_messages = {
            'nomeCategoria': {
                'required': 'Este campo não pode ser vazio.'
            },
        }

class RegisterCliente(forms.ModelForm):
    class Meta:
        model = Clientes
        fields = '__all__'
        labels = {
                'idCliente' : 'Identificação do Cliente',
                'nomeCliente' : 'Nome e Sobrenome',
                'cpf' : 'CPF',
                'telefone' : 'Telefone',
                'email' : 'E-mail',
                'endereco' : 'Endereço'
        }

        help_texts = {
            'nomeCliente': 'Digite nome e sobrenome',
        }

        error_messages = {
            'nomeCliente': {
                'required': 'Este campo não pode ser vazio.'
            },'cpf': {
                'required': 'Este campo não pode ser vazio.'
            },'telefone': {
                'required': 'Este campo não pode ser vazio.'
            },'email': {
                'required': 'Este campo não pode ser vazio.'
            },'endereco': {
                'required': 'Este campo não pode ser vazio.'
            },
        }

class RegisterItensPedidos(forms.ModelForm):
    class Meta:
        model = ItensPedidos
        fields = '__all__'
        labels = {
                'idItensPedidos' : 'Identidicação dos Itens Pedidos',
                'Quantidade' : 'Quantidade dos itens',
                'PrecoTotal' : 'Preço total do pedido',
                'Produto_idProduto' : 'Identificação dos produtos',
                'Pedidos_idPedidos' : 'Identificação do Pedido'

        }

        help_texts = {

        }

        error_messages = {
            'idItensPedidos': {
                'required': 'Este campo não pode ser vazio.'
            },

            'Quantidade': {
                'required': 'Informe a quantidade de produtos comprados.'
            },

            'PrecoTotal': {
                'required': 'Informe o preço total da compra.'
            },

            'Produto_idProduto': {
                'required': 'Informe os produtos comprados.'
            },

            'Pedidos_idPedidos': {
                'required': 'Informe a identificação deste pedido.'
            }

        }

class RegisterMetPagamento(forms.ModelForm):
    class Meta:
        model = MetodoPagamento
        fields = '__all__'
        labels = {
            'idMetodoPagamento' : 'ID: ',
            'nomeMetodo': 'Nome do método: ',
            'descricaoMetodo': 'Descrição: ',
        }

        help_texts = {
            'nomeMetodo': 'Digite o nome do método de pagamento.',
            'descricaoMetodo': 'Descrição do método.'
        }

        error_messages = {
            'nomeMetodo': {
                'required': 'Este campo não pode ser vazio.'
            },
            'descricaoMetodo': {
                'required': 'Descrição inválida'
            }
        }

class RegisterPedidos(forms.ModelForm):
    class Meta:
        model = Pedidos
        fields = '__all__'
        labels = {
                'idPedido' : 'Identidicação do Pedido',
                'Usuarios_idUsuario' : 'Identificação do Usuário',
                'DataEmissao' : 'Data de emissão do pedido',
                'StatusPedido' : 'Situação do pedido',
                'MetodoPagamento_idMetodoPagamento' : 'Método de pagamento'
        }

        help_texts = {
        }

        error_messages = {
            'Usuarios_idUsuario': {
                'required': 'Este campo não pode ser vazio.'
            },

            'MetodoPagamento_idMetodoPagamento': {
                'required': 'Selecione um método de pagamento'
            }
        }

class RegisterProdutos(forms.ModelForm):
    class Meta:
        model = Produtos
        fields = '__all__'
        labels = {
            'idProduto' : 'Identificação do Produto',
            'NomeProduto' : 'Nome do Produto',
            'Preco' : 'Preço',
            'Descricao' : 'Descrição do Produto',
            'Estoque' : 'Quantidade em estoque',
            'CategoriaProduto_idCategoriaProduto' : 'Categoria'

        }

        help_texts = {
            'NomeProduto': 'Digite o nome do produto.',
            'Preço': 'Quanto custará esse produto?',
            'Descricao' : 'Descreva as caracteristicas desse produto'
        }

        error_messages = {
            'nomeProduto': {
                'required': 'Este campo não pode ser vazio.'
            },
            'Preço': {
                'required': 'Defina um preço, o valor não pode ser nulo.'
            }
        }

apps/BancoDados/views.py
from django.shortcuts import render
from .forms import *

def view_cadcliente(request):
    form = RegisterCliente()
    return render(request, 'cadcliente.html', {'form': form})
def view_create_cliente(request):
    if request.POST:
        form = RegisterCliente(request.POST)
        form.save()
    else:
        form = RegisterCliente()
   
    return render(request, 'cadcliente.html', {'form': form, 'ok':'FUNCIONOU'})

def view_cadcategoria(request):
    form = RegisterCategoria()
    return render(request, 'cadcategoria.html', {'form': form})
def view_create_categoria(request):
    if request.POST:
        form = RegisterCategoria(request.POST)
        form.save()
    else:
        form = RegisterCategoria()
   
    return render(request, 'cadcategoria.html', {'form': form, 'ok':'FUNCIONOU'})

def view_caditenspedidos(request):
    form = RegisterItensPedidos()
    return render(request, 'caditenspedidos.html', {'form': form})
def view_create_itenspedidos(request):
    if request.POST:
        form = RegisterItensPedidos(request.POST)
        form.save()
    else:
        form = RegisterItensPedidos()
        
    return render(request, 'caditenspedidos.html', {'form': form, 'ok':'FUNCIONOU'})

def view_cadmetpagamento(request):
    form = RegisterMetPagamento()
    return render(request, 'cadmetpagamento.html', {'form': form})
def view_create_metpagamento(request):
    if request.POST:
        form = RegisterMetPagamento(request.POST)
        form.save()
    else:
        form = RegisterMetPagamento()
   
    return render(request, 'cadmetpagamento.html', {'form': form, 'ok':'FUNCIONOU'})

def view_cadpedido(request):
    form = RegisterPedidos()
    return render(request, 'cadpedido.html', {'form': form})
def view_create_pedido(request):
    if request.POST:
        form = RegisterPedidos(request.POST)
        form.save()
    else:
        form = RegisterPedidos()
        
    return render(request, 'cadpedido.html', {'form': form, 'ok':'FUNCIONOU'})

def view_cadproduto(request):
    form = RegisterProdutos()
    return render(request, 'cadproduto.html', {'form': form})
def view_create_produto(request):
    if request.POST:
        form = RegisterProdutos(request.POST)
        form.save()
    else:
        form = RegisterProdutos()
   
    return render(request, 'cadproduto.html', {'form': form, 'ok':'FUNCIONOU'})

apps/BancoDados/templates/cadcategoria.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Cadastro (Categoria)</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <h2>Cadastro de Categoria</h2>
    {{ok}}
    <form action="{% url 'bancodados:createcategoria' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <label for="{{field.id_for_label}}" > {{field.label}} :</label>
            {{field}} <br>
           
            {% if field.help_text %}
                <div style="color: rgb(158, 126, 126)">
                    {{field.help_text}}
                </div>
            {% endif %}

            {% if field.errors %}
                <div style="color: rgb(231, 9, 9)">
                    {{field.errors}}
                </div>
            {% endif %}

        {% endfor %}
        <button type="submit">Salvar</button>
    </form>

    {% comment %}
        {{ form }}
    {% endcomment %}
</body>
</html>

apps/BancoDados/templates/cadcliente.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title> Cadastro (Clientes) </title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <h2>Cadastro de Clientes </h2>
    {{ok}}
    <form action="{% url 'bancodados:createcliente' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <label for="{{field.id_for_label}}" > {{field.label}} :</label>
            {{field}} <br>
           
            {% if field.help_text %}
                <div style="color: rgb(158, 126, 126)">
                    {{field.help_text}}
                </div>
            {% endif %}

            {% if field.errors %}
                <div style="color: rgb(231, 9, 9)">
                    {{field.errors}}
                </div>
            {% endif %}

        {% endfor %}
        <button type="submit">Salvar</button>
    </form>

    {% comment %}
        {{ form }}
    {% endcomment %}
</body>
</html>

apps/BancoDados/templates/caditenspedidos.html
{% load static %}

{% block content %}

<link rel='stylesheet' type='text/css' media='screen' href="{% static 'css\crud.css' %}">
<body>
    <div class="crud">

        {% if messages %}
            <div class="mensagens">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <section class="wrapper">
            <h2>Cadastro de Produto</h2>
            <form action="{% url 'bancodados:createitenspedidos' %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <label for="{{field.id_for_label}}" > {{field.label}} :</label>
                    {{field}} <br>
                
                    <div class="help_text">
                        {% if field.help_text %}
                            {{field.help_text}}
                        {% endif %}
                    </div>

                    <div class="errors_text">
                        {% if field.errors %}
                            {{field.errors}}
                        {% endif %}
                    </div>
                {% endfor %}
                <br>
                <button type="submit">Salvar</button>
                <br>
                <a href="{% url 'usuarios:area_usuario' %}">Voltar para o área de usuário</a>
            </form>
        </section>
    </div>

</body>

{% endblock %}

apps/BancoDados/templates/cadmetpagamento.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Cadastro (Método de Pagamento)</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <h2>Cadastro de Método de Pagamento </h2>
    {{ok}}
    <form action="{% url 'bancodados:createmetpagamento' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <label for="{{field.id_for_label}}" > {{field.label}} :</label>
            {{field}} <br>
           
            {% if field.help_text %}
                <div style="color: rgb(158, 126, 126)">
                    {{field.help_text}}
                </div>
            {% endif %}

            {% if field.errors %}
                <div style="color: rgb(231, 9, 9)">
                    {{field.errors}}
                </div>
            {% endif %}

        {% endfor %}
        <button type="submit">Salvar</button>
    </form>

    {% comment %}
        {{ form }}
    {% endcomment %}
</body>
</html>

apps/BancoDados/templates/cadpedido.html
{% load static %}

{% block content %}

<link rel='stylesheet' type='text/css' media='screen' href="{% static 'css\crud.css' %}">
<body>
    <div class="crud">

        {% if messages %}
            <div class="mensagens">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <section class="wrapper">
            <h2>Cadastro de Produto</h2>
            <form action="{% url 'bancodados:createpedido' %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <label for="{{field.id_for_label}}" > {{field.label}} :</label>
                    {{field}} <br>
                
                    <div class="help_text">
                        {% if field.help_text %}
                            {{field.help_text}}
                        {% endif %}
                    </div>

                    <div class="errors_text">
                        {% if field.errors %}
                            {{field.errors}}
                        {% endif %}
                    </div>
                {% endfor %}
                <br>
                <button type="submit">Salvar</button>
                <br>
                <a href="{% url 'usuarios:area_usuario' %}">Voltar para o área de usuário</a>
            </form>
        </section>
    </div>

</body>

{% endblock %}

apps/BancoDados/templates/cadproduto.html
{% load static %}

{% block content %}

<link rel='stylesheet' type='text/css' media='screen' href="{% static 'css\crud.css' %}">
<body>
    <div class="crud">

        {% if messages %}
            <div class="mensagens">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <section class="wrapper">
            <h2>Cadastro de Produto</h2>
            <form action="{% url 'bancodados:createproduto' %}" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <label for="{{field.id_for_label}}" > {{field.label}} :</label>
                    {{field}} <br>
                
                    <div class="help_text">
                        {% if field.help_text %}
                            {{field.help_text}}
                        {% endif %}
                    </div>

                    <div class="errors_text">
                        {% if field.errors %}
                            {{field.errors}}
                        {% endif %}
                    </div>
                {% endfor %}
                <br>
                <button type="submit">Salvar</button>
                <br>
                <a href="{% url 'usuarios:area_usuario' %}">Voltar para o área de usuário</a>
            </form>
        </section>
    </div>

</body>

{% endblock %}