ElectroElite4/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from apps.core.views import *
from apps.BancoDados.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('user/', include('apps.core.urls')),
    path('crud/', include('apps.BancoDados.urls')),
]

apps/BancoDados/urls.py
from django.urls import path
from .views import *

app_name = 'bancodados'

urlpatterns = [
    path('cadcategoria/', view_cadcategoria),
    path('create_categoria/', view_create_categoria, name='createcategoria'),
    path('cadcliente/', view_cadcliente),
    path('create_cliente/', view_create_cliente, name='createcliente'),
    path('caditenspedidos/', view_caditenspedidos, name='caditenspedidos'),
    path('create_itenspedidos/', view_create_itenspedidos, name='createitenspedidos'),
    path('cadmetpagamento/', view_cadmetpagamento),
    path('create_metpagamento/', view_create_metpagamento, name='createmetpagamento'),
    path('cadpedido/', view_cadpedido, name='cadpedido'),
    path('create_pedido/', view_create_pedido, name='createpedido'),
    path('cadproduto/', view_cadproduto, name="cadproduto"),
    path('create_produto/', view_create_produto, name='createproduto'),
]

apps/core/urls.py
from django.urls import path
from .views import *

app_name = 'usuarios'

urlpatterns = [
    path('', view_home, name='home'),
    path('login/', view_login, name='login'),
    path('login/acess', view_acess_login, name='acess'),
    path('login/logout', view_logout, name= 'logout'),
    path('cadusuario/', view_cadusuario, name='cadastro'),
    path('cadusuario/<int:firstacess>', view_cadusuario, name='cadastro'),
    path('cadusuario/create_usuario/', view_create_usuario, name='createusuario'),
    path('area_usuario', view_area_usuario, name='area_usuario'),
]

templates/areausuario.html
{% load static %}

{% block content %}

<link rel='stylesheet' type='text/css' media='screen' href="{% static 'css\areausuario.css' %}">
<body>
    <!--
    
    <h1 style="color: white;">USER AREA </h1>
    
    {% if messages %}
        <div class="sucess">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    <div> Você está logado como: {{ request.user.username }} </div>

    -->

    <div class="container">
        <nav class="sidebar">
            <h1>ELECTROELITE4</h1>
            <ul>
                <li><a href="/">Voltar a página inicial</a></li>
                <li><a href="#profile">Perfil</a></li>
                <li><a href="#settings">Configurações</a></li>
                <li><a href="#messages">Mensagens</a></li>
                <li><a href="{% url 'usuarios:logout' %}">Sair</a></li>
            </ul>
        </nav>
        <main class="content">
            <section id="profile">
                <h2>Perfil do Usuário</h2>
                <div class="profile-info">
                    <div class="info-details">
                        <p><strong>Nome de Usuário:</strong> {{ user.username }} </p>
                        <p><strong>Nome e sobrenome:</strong> {{ user.first_name }} {{ user.last_name }} </p>
                        <p><strong>E-mail:</strong> {{ user.email }} </p>
                        <p><strong>Quantidade de Logins:</strong> {{ login_count }}</p>
                    </div>
                </div>
            </section>

            <section class="gerenciador" id="profile">
                <h2>Gerenciador</h2>
                    <div class="gerenciador_data">
                        
                        <div class="profile-info">
                            <div class="info-details">
                                <h2>Produtos</h2>
                                <a href="{% url 'bancodados:cadproduto' %}"> Adicionar produto</a> <br>
                                <a href=""> Editar produto</a> <br>
                                <a href=""> Remover produto</a>
                            </div>
                        </div>
                        
                        <div class="profile-info">          
                            <div class="info-details">
                                <h2>Pedidos</h2>
                                <a href="{% url 'bancodados:cadpedido' %}"> Adicionar pedido</a> <br>
                                <a href=""> Editar pedido</a> <br>
                                <a href=""> Remover pedido</a>
                            </div>
                        </div>

                        <div class="profile-info">
                            <div class="info-details">
                                <h2>Itens Pedidos</h2>
                                <a href="{% url 'bancodados:caditenspedidos' %}"> Adicionar Itens Pedidos</a> <br>
                                <a href=""> Editar Itens Pedidos</a> <br>
                                <a href=""> Remover Itens Pedidos</a>
                            </div>
                        </div>

                    </div>       
            </section>

        </main>
    </div>

    <!--
    <div>
        <form action="{% url 'usuarios:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit"> Logout </button>
        </form>
    </div>
    -->

{% endblock %}

templates/cadusuario.html
{% extends "base/master.html" %}

{% load static %}

{% block content %}

<link rel='stylesheet' type='text/css' media='screen' href="{% static 'css\cadastro.css' %}">
<body>
    <div class="divcadastro">
    
        {% if form.errors %}
            <div class="errors">
                <p> Corrija os erros a seguir. </p>
            </div>
        {% endif %}
        
        {% if messages %}
        <div class="sucess">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
        {% endif %}
        
        <div class="wrapper">
            <h1>Cadastro</h1>
            
            <form action="{% url 'usuarios:createusuario' %}" method="post">
                
                {% csrf_token %}
                {% for field in form %}

                    <p><label for="{{field.id_for_label}}" > {{field.label}} :</label>
                    {{field}} <br>
                    <div class="help_text">
                        {% if field.help_text %}
                            {{ field.help_text }}
                        {% endif %}
                    </div>
                    <p>
                    
                    <div class="errors_text">
                    {% if field.errors %}
                            {{field.errors}}
                    {% endif %}
                    </div>
                    
                {% endfor %}

                <button type="submit">Cadastrar</button>
                <p> Já possui uma conta? <a href="{% url 'usuarios:login' %}">Login aqui!</a></p>
                
            </form>
        </div>
    </div>

    {% comment %}
        {{ form }}
    {% endcomment %}

</body>

{% endblock %}

templates/home.html
{% extends "base/master.html" %}
{% load static %}
{% block content %}

<link rel='stylesheet' type='text/css' media='screen' href="{% static 'css\home.css' %}">
<body>
    <!--==================== MAIN ====================-->
    <main class="main">
        <!--==================== HOME ====================-->
        <section class="home section" id="Home" style="background-image: url('static/img/Fundo.png')">

            <div class="home_data container">
                <img class="home_img" src="{% static '\img\Logo.png' %}" alt="logo">
            </div>

        </section>

        <!--==================== GALAXYS23 ====================-->

        <section class="galaxy">
            <h2 class="section_titulo">DESTAQUE</h2>
                   
            <div class="galaxy_data container">
                <div class="galaxy_texto">
                    <h2>Galaxy S23 Ultra</h2>
                    <p>Para você que está a procura de um novo smartphone e dar aquele upgrade no seu dia a dia no trabalho ou para navegar nas redes sociais, precisa conhecer o Samsung Galaxy S23 Ultra. É o smartphone top de linha para quem quer muito desempenho e câmera de arrasar.</p>
                    <a href="#" class="galaxy_btn">Comprar</a>
                </div>

                <div class="galaxy_img">
                    <img src="{% static '\img\s23.png' %}" alt="galaxys23">
                </div>

            </div>
        </section>

        <!--==================== MACBOOK PRO ====================-->

        <section class="macbook">

            <div class="macbook_data container">
                <h1>Macbook PRO</h1>
                <h2>Arrepia. Até na Beleza.</h2>
                <img src="{% static '\img\macbook.png' %}"v alt="">
                <p>R$ 29.999,00 à vista ou 10x de 2.999,90</p>
                <a href="" class="macbook_btn">Comprar</a>
            </div>

        </section>

        <!--==================== SMARTPHONES ====================-->

        <section class="smartphones">

            <h2 class="section_titulo">SMARTPHONES</h2>

            <div class="smartphones_data grid">

                <div class="smartphone_card">
                    <img class="smartphone_img" src="{% static '\img\1.png' %}" alt="Iphone 11">
                    <h2 class="smartphone_titulo">Iphone 11</h2>
                    <p class="smartphone_subtitulo">256GB/6 - Lacrado - 1 ano de garantia Apple</p>
                    <p class="smartphone_subtitulo2">R$ 7.990,00 à vista ou 12x de R$ 772,63</p>
                    <a href="" class="macbook_btn">Comprar</a>
                </div>

                <div class="smartphone_card">
                    <img class="smartphone_img" src="{% static '\img\2.webp' %}" alt="Galaxy S24">
                    <h2 class="smartphone_titulo">Galaxy S24</h2>
                    <p class="smartphone_subtitulo">256GB/6 - Lacrado - 1 ano de garantia Samsung</p>
                    <p class="smartphone_subtitulo2">R$ 3.990,00 à vista ou 12x de R$ 380,63</p>
                    <a href="" class="macbook_btn">Comprar</a>
                </div>

                <div class="smartphone_card">
                    <img class="smartphone_img" src="{% static '\img\3.webp' %}" alt="F6 Pro">
                    <h2 class="smartphone_titulo">Xiaomi Poco F6 PRO </h2>
                    <p class="smartphone_subtitulo">256GB/6 - Lacrado - 1 ano de garantia Xiaomi</p>
                    <p class="smartphone_subtitulo2">R$ 1.990,00 à vista ou 12x de R$ 180,63</p>
                    <a href="" class="macbook_btn">Comprar</a>
                </div>

                <div class="smartphone_card">
                    <img class="smartphone_img" src="{% static '\img\4.png' %}" alt="Iphone 13 Pro">
                    <h2 class="smartphone_titulo">Iphone 13 Pro</h2>
                    <p class="smartphone_subtitulo">256GB/6 - Lacrado - 1 ano de garantia Apple</p>
                    <p class="smartphone_subtitulo2">R$ 4.990,00 à vista ou 12x de R$ 450,63</p>
                    <a href="" class="macbook_btn">Comprar</a>
                </div>
            </div>
        </section>
    </main>
</body>

{% endblock %}

templates/login.html
{% extends "base/master.html" %}

{% load static %}

{% block content %}

<link rel='stylesheet' type='text/css' media='screen' href="{% static 'css\login.css' %}">
<body>
    <div class="divlogin">

        {% if messages %}
            <div class="mensagens">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
        {% endif %}

        <section class="wrapper">
            <h1>Login</h1>
            <form action="{% url 'usuarios:acess' %}" method="post">
                {% csrf_token %}

                {{form}}

                <button type="submit"> Login </button>
            </form>
            
            <p>Não possui uma conta? <a href="{% url 'usuarios:cadastro' %}">Crie sua conta aqui!</a></p>
        </section>
    </div>
</body>

{% endblock %}